# Schema for the views plugins of the Workbench Access module.

views.field.workbench_access_section:
  type: views_field
  label: 'Workbench Section'
  mapping:
    separator:
      type: label
      label: 'Separator'
views.field.workbench_access_user_section:
  type: views_field
  label: 'Workbench Section'
  mapping:
    separator:
      type: label
      label: 'Separator'
views.filter.workbench_access_section:
  type: views_filter
  label: 'Workbench Section'
  mapping:
    operator:
      type: string
      label: 'Operator'
    value:
      type: sequence
      label: 'Values'
      sequence:
        type: string
        label: 'Value'
    expose:
      type: mapping
      label: 'Expose'
      mapping:
        reduce:
          type: integer
          label: 'Reduce'
    reduce_duplicates:
      type: integer
      label: 'Reduce duplicates'
    section_filter:
      type: mapping
      label: 'Section Filter'
      mapping:
        show_hierarchy:
          type: integer
          label: 'Show Hierarchy'
